Add PATCH method to the project resource for partially updating an existing project
DependencyTrack/dependency-track pull request #1586
Opened 2022-05-05 19:24 UTC by sephiroth-j

This eases project management by removing the need to fetch a project at first, modifying the parts of interest and updating the project in total.
For example , it is now possible to change the `active` property from `true` to `false` without touching other properties.

Please note that I had to change the behavior of `Project#isActive` to return `null` if `active` is actually `null`. In order not to change the API response, `null` is serialized as `true` with a custom `JsonSerializer`, thus keeping the behavior the same externally.

2022-05-06 10:59 UTC, valentijnscholten commented
Curious, did you try using the `isDirty` functionality built-in to JDO/Nucleus to see a write to the DB is needed?

2022-05-06 20:22 UTC, nscuro requested changes
Thanks for the PR! I also found myself wanting such a functionality in the past on multiple occasions. Few minor nitpicks, other than that it looks good to me.

2022-05-06 20:22 UTC, nscuro commented on src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
> +    public void patchProjectTest() {
Can we split these 4 test cases into separate methods? Makes it easier to spot what went wrong in build logs, but also reduces cognitive complexity. Currently you need to keep track of whether e.g. `p1` is modified and *how* throughout the method.

2022-05-06 20:22 UTC, nscuro commented on src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
> +    private <T> boolean copyIfDifferent(final Project source, final Project target, final Function<Project, T> getter, final BiConsumer<Project, T> setter) {
Nitpick: It's less copying and more setting. Rename this to `setIfDifferent` maybe?

2022-05-07 16:00 UTC, sephiroth-j commented
I have touched up the bits, please review them again.

2022-05-07 20:50 UTC, nscuro approved these changes

2022-05-07 20:50 UTC, merged