Add a Jira Publisher to publish Dependency Track alerts to Jira tickets
DependencyTrack/dependency-track pull request #2119
Opened 2022-11-04 19:14 UTC by Mvld3r

Addresses #2118

2022-11-15 11:18 UTC, nscuro requested changes
Thanks for the PR, @Mvld3r!

Only two minor things to address please.

2022-11-15 11:18 UTC, nscuro commented on docs/_docs/integrations/notifications.md
> +- For Slack: Mattermost and Microsoft Teams: it's the incoming webhook URL generated from each respective
Minor typo:

```suggestion
- For Slack, Mattermost and Microsoft Teams: it's the incoming webhook URL generated from each respective
```

2022-11-18 09:00 UTC, nscuro approved these changes
Thanks @Mvld3r! 🚀

2022-11-20 15:03 UTC, merged

2022-11-29 12:31 UTC, rightphp commented
@nscuro are we planning to release it into 4.7 milestone or earlier to that?