Issue 2109 : alias attribution
DependencyTrack/dependency-track pull request #2161
Opened 2022-11-17 09:57 UTC by sahibamittal

Signed-off-by: Sahiba Mittal <sahibamittal98@gmail.com>

Issue: https://github.com/DependencyTrack/dependency-track/issues/2109

2022-11-17 17:10 UTC, sahibamittal commented
@sonatype-lift ignoreall

2022-11-21 16:17 UTC, nscuro requested changes
Some initial feedback. Still have not tested it yet as I'm currently working over mobile hotspot and can't download too much data. 😅

2022-11-21 16:17 UTC, nscuro commented on src/main/java/org/dependencytrack/util/VulnerabilityUtil.java
> +    public static void checkInactiveAttributions(final QueryManager qm,
Nitpick: The name should say `AliasAttribution` instead of just `Attribution`, as we have multiple types of attributions right now.

2022-11-21 16:17 UTC, nscuro commented on src/main/java/org/dependencytrack/model/AliasAttribution.java
> +public class AliasAttribution implements Serializable {
Maybe name this `VulnerabilityAliasAttribution`?

2022-11-21 16:17 UTC, nscuro commented on src/main/java/org/dependencytrack/model/AliasAttribution.java
> +@PersistenceCapable
This class will need to be added to `persistence.xml`.

2023-01-26 10:17 UTC, closed without merging