chore: added swagger types for BOM operations
DependencyTrack/dependency-track pull request #2230
Opened 2022-12-04 08:13 UTC by omerlh

### Description

I was working on generating a typescript client using Swagger (happy to contribute the client also!) and I noticed some APIs does not have well defined responses.

### Addressed Issue

### Additional Details

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/github-templates/CONTRIBUTING.md#pull-requests)
- [ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

I am not sure how I should test it, so happy to get some feedback on the change!

2022-12-04 09:48 UTC, valentijnscholten commented
Can I suggest to submit a PR with only the changes you propose? Currently 90% seems to be only linting?

2022-12-04 09:53 UTC, omerlh commented
Yes, sorry - fixed. VS code did things I didn't noticed...

2022-12-04 23:26 UTC, nscuro commented
You'll find lots of these inconsistencies, which is why I can't really recommend generating clients from the swagger doc. See #840.

2022-12-05 06:02 UTC, omerlh commented
I don't mind keep fixing it as I'm going, I have a client that works pretty well and generated from Swagger. If this is acceptable by you, OFC...

2022-12-05 12:55 UTC, nscuro requested changes
I guess I'm fine with small incremental improvements until we have a better OpenAPI doc in place. 

A few minor adjustments and clarifications.

2022-12-06 05:39 UTC, omerlh commented on src/main/java/org/dependencytrack/model/PortfolioMetrics.java
> +    @NotNull
Yes, I wasn't sure which one is better to use, I can change it.

2022-12-06 05:42 UTC, omerlh commented on src/main/java/org/dependencytrack/resources/v1/vo/BomUploadResponse.java
> +    private static final long serialVersionUID = -7592438786581683855L;
Yes, I copied it from another class and just changed some numbers. Changing more numbers now.

2022-12-06 07:46 UTC, omerlh commented
I think the build failure are not related to my changes

2022-12-06 09:43 UTC, nscuro commented
@omerlh Sorry about that, #2241 should fix the build failure. If you rebase with `master` it should work again.

2022-12-06 11:06 UTC, omerlh commented
Ok, rebased

2022-12-06 11:40 UTC, nscuro approved these changes
Thanks @omerlh! 🚀

2022-12-06 11:41 UTC, merged