Checking policies violated intead of violations to fix ALL-policy
DependencyTrack/dependency-track pull request #2336
Opened 2022-12-28 16:36 UTC by malice00

### Description

Checking the actual number of policies violated instead of the number of violations found, since this can be different and it broke policy that are configured for ALL conditions to (not) match.

### Addressed Issue

Fixes #1924

### Additional Details

Using the return-value of 'List.addAll' to check if any violations were added by the evaluator to add 1 to the counter. Changed the check on 'ANY' to also use this counter for a little performance-gain.

Also found a bug in the method `evaluate(List)`, which until now only returned the **last** list of violations instead of all -- found this because my new test wasn't failing on the old code although it should have.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/github-templates/CONTRIBUTING.md#pull-requests)
- [X] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

2023-01-27 17:01 UTC, nscuro requested changes
Thanks @malice00 for tackling this, makes sense to me. Just a minor suggestion on variable naming.

2023-01-27 23:50 UTC, malice00 commented on src/main/java/org/dependencytrack/policy/PolicyEngine.java
> +                int policiesViolated = 0;
Minor or not, it makes sense. :-)
Rebased the branch to the current master and changed the name.

2023-01-27 23:57 UTC, nscuro approved these changes

2023-01-28 00:21 UTC, merged

2023-02-06 09:18 UTC, msymons commented
As spotted by @malice00, this PR does not cover the use case that is now logged as #2455:   a policy that has multiple of the same types of conditions and its operator set to AND.