Support for CPAN repository
DependencyTrack/dependency-track pull request #2593
Opened 2023-03-10 21:59 UTC by walterdeboer

### Description

Support for CPAN repository

### Addressed Issue

Closes #639 

### Additional Details

### Checklist

- [x] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
- [ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [x] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- [x] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

2023-03-11 17:05 UTC, nscuro approved these changes

2023-03-12 15:03 UTC, nscuro requested changes

2023-03-13 07:33 UTC, walterdeboer commented on src/main/java/org/dependencytrack/tasks/scanners/SnykAnalysisTask.java
> +            "cpan", // Not defined in StandardTypes
Check, fixed

2023-03-16 20:35 UTC, nscuro approved these changes
Thanks @walterdeboer!

2023-03-16 20:35 UTC, merged