Subject prefix
DependencyTrack/dependency-track pull request #3422
Opened 2024-01-31 09:20 UTC by LaVibeX

### Description

- Email Subject Prefix is Hardcoded rightnow `.subject("[Dependency-Track] " + notification.getTitle())`, 
- This is a solution to allow the User to modify the Subject Prefix to its will  `.subject(smtpPrefix + " " + notification.getTitle() )`

This modification would be available in `Administration>Configuration>Email` 
and ` "[Dependency-Track]"` would be the first default value. 

If the User change the Subject Prefix, it will need to press Update button in order to save the changes.
Subject Prefix is **not a required field** so leaving the input box in blank is also an option.

 **_This new feature helps to distinguish between several instances of Dependency-Track, e.g. prod and qual systems._**

### Default value: _[Dependency-Track]_
![image](https://github.com/DependencyTrack/dependency-track/assets/52439101/4aba3cc6-198b-4799-988c-9c2d6a644f0f)
### Modified Value:  _[Dependency-Track TEST ®]_
![image](https://github.com/DependencyTrack/dependency-track/assets/52439101/0ed589d4-8c65-47fe-990f-83c1657f729e)
### Modified Value: " "
![image](https://github.com/DependencyTrack/dependency-track/assets/52439101/129beb2e-f7b0-461e-90b4-5c5d7aa583c9)

This PR depends from the corresponding **frontend** PR. 

### Addressed Issue
This fixes https://github.com/DependencyTrack/dependency-track/issues/1823

### Additional Details 
Check if smtpPrefix is null in order to clean the value to " "
`smtpPrefix = smtpPrefix == null ? " " : smtpPrefix;`

This PR is supervised by @lukas-braune.

### Checklist

- [x] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
- [ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [x] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

Signed-off-by: Andres Tito <andres.tito@rohde-schwarz.com>

2024-01-31 19:41 UTC, valentijnscholten requested changes

2024-01-31 19:41 UTC, valentijnscholten commented on src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java
> +                    .subject(smtpPrefix + " " + notification.getTitle() )
Might be nitpicking, but I suggest to change the name of the variable and setting to something more generic like `emailSubjectPrefix` or something like that. The prefix is not really tied to the SMTP protocol. If other email delivery methods are added in the future, the prefix might still be valid to use, but should not be called `smtpPrefix`.

2024-02-04 16:57 UTC, nscuro approved these changes
Thanks @LaVibeX!

2024-02-05 10:45 UTC, nscuro commented
Looks like this broke `SendMailPublisherTest`. Do you mind having a look @LaVibeX?

2024-02-05 18:01 UTC, nscuro approved these changes

2024-02-05 18:02 UTC, merged

2024-02-06 07:41 UTC, girtsn commented
it says that it implements https://github.com/DependencyTrack/dependency-track/issues/1823
from the ticket "add the notification subject configuration to the notification template and use same params as there exists for content"
is it possible to use variables now as in body of the notification (e.g. severity / others)? the description of this ticket seems to be about adding a static prefix only?

2024-02-07 15:19 UTC, nscuro commented
You are right @girtsn, I reopened the issue.