Fix vex export returning invalid CycloneDX
DependencyTrack/dependency-track pull request #3948
Opened 2024-07-08 22:06 UTC by SaberStrat

### Description

Fixes exported VEX and BOMs with vulnerabilities not conforming to CycloneDX 1.5.

### Addressed Issue

#3834 

### Additional Details

The general idea was to deduplicate vulnerabilities by accumulating unique affected components (on bom with vulnerabilities export) or project (on vex export) per vulnerability.

I settled with the implementation with two HashMaps, one (the one doing the actual work) mapping vulnerability ids to AffectRefs sets, the other (the assisting one) mapping AffectRefs to Affect objects, and deciding whether to create a new vulnerability key or append to an existing one based on the vulnerability existing in the HashMap keys or not.

It seemed like the simplest and most 'local' solution, without creating additional structures or references at more remote code places.

In particular, other possible implementations I considered were 
1. reducing the two HashMaps down to just the one mapping vulnids to Affects. However, this would require either creating a class extending the Affect class or making Affect a `record`, the latter requiring creating a new cyclonedx-core lib version.
2. passing an affects List to Vulnerability's convert() method.

### Checklist

- [x] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
- [x] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [ ] ~This PR implements an enhancement, and I have provided tests to verify that it works as intended~
- [ ] ~This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)~
- [ ] ~This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly~

2024-07-21 15:17 UTC, nscuro requested changes

2024-07-21 15:17 UTC, nscuro commented on src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporterTest.java
> +    public void testSchemaValidityOfExportedVexWithMultipleComponentsWithSameVulnerability() throws GeneratorException {
Consider moving this to [`VexResourceTest`](https://github.com/DependencyTrack/dependency-track/blob/master/src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java), and asserting the entire response JSON.

Also, a test case that demonstrates what happens when `componentA` and `componentB` have different analyses (i.e. one is suppressed the other is not, or one has sate `IN_TRIAGE` the other `EXPLOITABLE`) would be good.

If we de-duplicate vulnerabilities without the `Analysis` in mind, we might drop important data.

2024-07-21 15:43 UTC, SaberStrat commented on src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporterTest.java
> +    public void testSchemaValidityOfExportedVexWithMultipleComponentsWithSameVulnerability() throws GeneratorException {
Yeah I'm re-implementing it such that the whole Vulnerability object is used for comparison. Still in the process of making it work.

Will do what you wrote with the tests.

2024-07-28 06:42 UTC, SaberStrat commented on src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporterTest.java
> +    public void testSchemaValidityOfExportedVexWithMultipleComponentsWithSameVulnerability() throws GeneratorException {
Done

2024-08-06 19:51 UTC, nscuro commented
@SaberStrat cyclonedx-core-java 9.0.5 was [released earlier today](https://github.com/CycloneDX/cyclonedx-core-java/releases/tag/cyclonedx-core-java-9.0.5), which includes your changes. You should be able to bump the library version now to make your implementation work.

2024-08-07 21:30 UTC, SaberStrat commented
cyclonedx-core-java bumped and rebased to master.

2024-08-09 06:38 UTC, SaberStrat commented
@nscuro I take it adding escaped quotes to the expected error messages in the test methods is not a proper solution for this?

2024-08-09 06:42 UTC, nscuro commented
Yup! Nothing special to do on our side since we merely forward the error messages. But still good to have such tests to be made aware of *when* these things change.

2024-08-09 21:29 UTC, SaberStrat commented
Rinse and repeat. This time, I ran the full test suite locally and it passed.

Should I cleanup/squash the commits down logically?

2024-08-09 21:42 UTC, nscuro commented
> Should I cleanup/squash the commits down logically?

Not necessary.

2024-08-09 22:20 UTC, nscuro approved these changes
Thanks @SaberStrat! I'll also backport this to v4.11.6.

2024-08-09 22:20 UTC, merged