fix: fix anchors in changelog documentation
DependencyTrack/dependency-track pull request #3965
Opened 2024-07-10 10:22 UTC by JCHacking

### Description
Fixed the problem where the links for the changelog in the web documentation were not being generated correctly

### Addressed Issue
#2094 

### Checklist

- [X] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
- [X] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

2024-07-10 10:30 UTC, JCHacking commented
As far as I can see it was failing because it always caught the id of the last h6 (Software Bill of Materials).

If we set the ids to be generated, it works in the versions, but in the files it still fails.

2024-07-10 10:56 UTC, nscuro commented
Thanks for looking into this!

> Where are these links generated?

They are generated by https://github.com/allejo/jekyll-anchor-headings which is located here in the repo: https://github.com/DependencyTrack/dependency-track/blob/master/docs/_includes/anchor_headings.html

To be honest I added it a while ago due to a lack of better options - before adding it there were no anchors at all. I'm saying this because there *may* be better options out there that do the job more reliably, so please feel free to experiment with other options as you see fit.

2024-07-10 11:03 UTC, JCHacking commented
I have checked the tool and it seems that when in a markdown there is a h1 - h6 it automatically generates an id, which is translated into an anchor. So with archives there is no automatic solution, the only one would be to generate the markdown from _post to add the link.

2024-07-18 05:14 UTC, JCHacking commented
Hi @nscuro 
After a thorough review, I don't see a better way to do all this, this is the best that can be achieved with Jekyll.

Do you want to put links to the files of each release? For this we would have to modify the _post, they are generated automatically? 

If so, I can edit the existing ones and make the new ones incorporate it, as long as you are ok with it.

2024-07-21 15:08 UTC, nscuro commented
Thanks for investigating!

> Do you want to put links to the files of each release? For this we would have to modify the _post, they are generated automatically?

If specifying the links manually fixes the issue, then I'd say let's go with that. It may be tedious, but IMO the important part is that they *work* :D

Would be much appreciated if you could do that!

2024-07-21 16:18 UTC, JCHacking commented
Hi @nscuro 
Modified all _posts with a script (Sorry so many commits, you can see better from github the differences than from git by console)

2024-07-21 19:34 UTC, nscuro requested changes

2024-07-21 19:34 UTC, nscuro commented on docs/_posts/2024-07-08-v4.11.5.md
> +###### [frontend-dist.zip](https://github.com/DependencyTrack/dependency-track/releases/download/4.11.5/frontend-dist.zip)
Frontend links should point to the `DependencyTrack/frontend` repository. The current links yield a 404.

```suggestion
###### [frontend-dist.zip](https://github.com/DependencyTrack/frontend/releases/download/4.11.5/frontend-dist.zip)
```

2024-07-21 20:21 UTC, JCHacking commented
I didn't notice that case, fixed in all files

2024-07-21 20:38 UTC, nscuro approved these changes
Thanks!

2024-07-21 20:39 UTC, merged